// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";
import { processEvalQueueBatch } from "./src/server/eval-queue/consumer";

export default {
  fetch: handler.fetch,

  async queue(batch, env, ctx) {
    await processEvalQueueBatch(batch as MessageBatch<import("./src/server/runtime/cloudflare").EvalJobQueueMessage>, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
